
name: Broken Action 3 - Run script

on:
  pull_request: 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-base

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run python script
        run: |
          echo "Running python here"
          python3 01-python_test.py
