
name: Broken Action 2 - Create an issue

on:
  pull_request: 
  workflow_dispatch:

jobs:
  hello:
   runs-on: ubuntu-latest
    steps:

      - name: Hello World
        run: echo "hello world"

      - name: Checkout files
        uses: actions/checkout@v3

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ./utils/issue-template.md
